# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-Intraweb
version:      1.02
version_from: lib/Acme/Intraweb.pm
installdirs:  site
requires:
    CPANPLUS:                      0.036

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
